import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import "./style.css";
const API=import.meta.env.VITE_WRITING_API||"http://localhost:9899/api";
const blank={title:"",type:"SHAYARI",content:"",isPublic:false};
function App(){
 const [mode,setMode]=useState("home"),[token,setToken]=useState(localStorage.getItem("writingToken")),[role,setRole]=useState(localStorage.getItem("writingRole")),[items,setItems]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(token)load(role==="OWNER"?"private":"public")},[token,role]);
 async function load(kind){setBusy(true);try{const r=await fetch(API+"/writings/"+kind,{headers:{Authorization:"Bearer "+token}});if(r.status===401){logout();return}if(!r.ok)throw Error();setItems(await r.json());}catch{setError("Could not load writings. Check the backend connection.")}finally{setBusy(false)}}
 async function login(path,body){setError("");setBusy(true);try{const r=await fetch(API+"/access/"+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||"Invalid access details");return}localStorage.setItem("writingToken",d.accessToken);localStorage.setItem("writingRole",d.role);setToken(d.accessToken);setRole(d.role);setMode(d.role==="OWNER"?"dashboard":"library");}catch{setError("Unable to connect to the writing service.")}finally{setBusy(false)}}
 async function save(e){e.preventDefault();setBusy(true);setError("");try{const url=editing?API+"/writings/"+editing:API+"/writings";const r=await fetch(url,{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Save failed");setForm(blank);setEditing(null);await load("private");}catch(err){setError(err.message||"Could not save writing.")}finally{setBusy(false)}}
 async function remove(id){if(!window.confirm("Delete this writing?"))return;setBusy(true);try{const r=await fetch(API+"/writings/"+id,{method:"DELETE",headers:{Authorization:"Bearer "+token}});if(!r.ok)throw Error();await load("private")}catch{setError("Could not delete this writing.")}finally{setBusy(false)}}
 async function logout(){const t=token;try{if(t)await fetch(API+"/access/logout",{method:"POST",headers:{Authorization:"Bearer "+t}})}finally{localStorage.removeItem("writingToken");localStorage.removeItem("writingRole");setToken(null);setRole(null);setItems([]);setMode("home")}}
 const theme=(editing?form.type:items[0]?.type||"NOTE").toLowerCase();
 if(!token||mode==="home")return <main className="shell home"><div className="hero"><span className="eyebrow">WRITING VAULT</span><h1>Your words.<br/><i>Your space.</i></h1><p>A private place for shayari, stories and everything you want to remember.</p><div className="actions"><button onClick={()=>setMode("owner")}>Owner Login</button><button className="ghost" onClick={()=>setMode("public")}>Public Access</button></div></div>{mode==="owner"&&<Login title="Owner Login" fields={["username","password"]} submit={v=>login("owner",v)} error={error} busy={busy} close={()=>setMode("home")}/>} {mode==="public"&&<Login title="Enter 4-digit code" fields={["code"]} submit={v=>login("public",v)} error={error} busy={busy} close={()=>setMode("home")}/>}</main>;
 if(role==="OWNER")return <main className={"shell "+theme}><header><b>Writing Vault</b><button className="ghost" onClick={logout}>Logout</button></header><section className="dashboard"><div><span className="eyebrow">{editing?"EDIT":"CREATE"}</span><h2>{editing?"Edit writing.":"Write something."}</h2><form onSubmit={save}><input placeholder="Title" maxLength="120" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>SHAYARI</option><option>STORY</option><option>NOTE</option></select><textarea placeholder="Write here..." maxLength="50000" value={form.content} onChange={e=>setForm({...form,content:e.target.value})} required/><label><input type="checkbox" checked={form.isPublic} onChange={e=>setForm({...form,isPublic:e.target.checked})}/> Make public</label><div className="actions"><button disabled={busy}>{busy?"Saving…":editing?"Update":"Save Writing"}</button>{editing&&<button type="button" className="ghost" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div>{error&&<small>{error}</small>}</form></div><Library items={items} owner busy={busy} onEdit={x=>{setEditing(x.id);setForm({title:x.title,type:x.type,content:x.content,isPublic:x.public})}} onDelete={remove}/></section></main>;
 return <main className={"shell "+theme}><header><b>Writing Vault</b><button className="ghost" onClick={logout}>Exit</button></header><Library items={items} publicView busy={busy}/></main>;
}
function Login({title,fields,submit,error,busy,close}){const[v,setV]=useState({});return <div className="card login"><button type="button" className="close ghost" onClick={close}>×</button><h2>{title}</h2><form onSubmit={e=>{e.preventDefault();submit(v)}}>{fields.map(f=><input key={f} type={f==="password"?"password":"text"} inputMode={f==="code"?"numeric":undefined} autoComplete={f==="password"?"current-password":"off"} maxLength={f==="code"?4:undefined} pattern={f==="code"?"[0-9]{4}":undefined} placeholder={f==="code"?"4-digit code":f} onChange={e=>setV({...v,[f]:e.target.value})} required/>)}<button disabled={busy}>{busy?"Checking…":"Continue"}</button>{error&&<small>{error}</small>}</form></div>}
function Library({items,publicView,owner,onEdit,onDelete,busy}){return <section className="library"><div className="library-head"><span className="eyebrow">{publicView?"PUBLIC WRITINGS":"YOUR WRITINGS"}</span><span className="muted">{items.length} {items.length===1?"writing":"writings"}</span></div>{busy&&items.length===0?<p className="muted">Loading…</p>:items.length===0?<p className="muted">Nothing here yet.</p>:items.map(x=><article className={"writing "+x.type.toLowerCase()} key={x.id}><span>{x.type}</span><h3>{x.title}</h3><p>{x.content}</p><em>{x.public?"Public":"Private"}</em>{owner&&<div className="actions"><button className="ghost" onClick={()=>onEdit(x)}>Edit</button><button className="ghost danger" disabled={busy} onClick={()=>onDelete(x.id)}>Delete</button></div>}</article>)}</section>}
createRoot(document.getElementById("root")).render(<App/>);