import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import "./style.css";
const API=import.meta.env.VITE_WRITING_API||"http://localhost:9899/api";
function App(){
 const [mode,setMode]=useState("home"),[token,setToken]=useState(localStorage.getItem("writingToken")), [role,setRole]=useState(localStorage.getItem("writingRole")), [items,setItems]=useState([]),[form,setForm]=useState({title:"",type:"SHAYARI",content:"",isPublic:false}),[error,setError]=useState("");
 useEffect(()=>{if(token) load(role==="OWNER"?"private":"public")},[token,role]);
 async function load(kind){const r=await fetch(API+"/writings/"+kind,{headers:{Authorization:"Bearer "+token}});if(r.ok)setItems(await r.json());}
 async function login(path,body){setError("");const r=await fetch(API+"/access/"+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError("Invalid access details");return}const d=await r.json();localStorage.setItem("writingToken",d.accessToken);localStorage.setItem("writingRole",d.role);setToken(d.accessToken);setRole(d.role);setMode(d.role==="OWNER"?"dashboard":"library");}
 async function save(e){e.preventDefault();const r=await fetch(API+"/writings",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify(form)});if(r.ok){setForm({title:"",type:"SHAYARI",content:"",isPublic:false});load("private");}}
 const theme=items[0]?.type?.toLowerCase()||form.type.toLowerCase();
 if(!token||mode==="home")return <main className="shell home"><div className="hero"><span className="eyebrow">WRITING VAULT</span><h1>Your words.<br/><i>Your space.</i></h1><p>A private place for shayari, stories and everything you want to remember.</p><div className="actions"><button onClick={()=>setMode("owner")}>Owner Login</button><button className="ghost" onClick={()=>setMode("public")}>Public Access</button></div></div>{mode==="owner"&&<Login title="Owner Login" fields={["username","password"]} submit={v=>login("owner",v)} error={error}/>} {mode==="public"&&<Login title="Enter 4-digit code" fields={["code"]} submit={v=>login("public",v)} error={error}/>}</main>;
 if(role==="OWNER")return <main className={"shell "+theme}><header><b>Writing Vault</b><button className="ghost" onClick={()=>{localStorage.clear();location.reload()}}>Logout</button></header><section className="dashboard"><div><span className="eyebrow">CREATE</span><h2>Write something.</h2><form onSubmit={save}><input placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>SHAYARI</option><option>STORY</option><option>NOTE</option></select><textarea placeholder="Write here..." value={form.content} onChange={e=>setForm({...form,content:e.target.value})} required/><label><input type="checkbox" checked={form.isPublic} onChange={e=>setForm({...form,isPublic:e.target.checked})}/> Make public</label><button>Save Writing</button></form></div><Library items={items}/></section></main>;
 return <main className={"shell "+theme}><header><b>Writing Vault</b><button className="ghost" onClick={()=>{localStorage.clear();location.reload()}}>Exit</button></header><Library items={items} publicView/></main>;
}
function Login({title,fields,submit,error}){const [v,setV]=useState({});return <div className="card login"><h2>{title}</h2><form onSubmit={e=>{e.preventDefault();submit(v)}}>{fields.map(f=><input key={f} type={f==="password"?"password":"text"} inputMode={f==="code"?"numeric":undefined} maxLength={f==="code"?4:undefined} placeholder={f==="code"?"4-digit code":f} onChange={e=>setV({...v,[f]:e.target.value})} required/>)}<button>Continue</button>{error&&<small>{error}</small>}</form></div>}
function Library({items,publicView}){return <section className="library"><span className="eyebrow">{publicView?"PUBLIC WRITINGS":"YOUR WRITINGS"}</span>{items.length===0?<p className="muted">Nothing here yet.</p>:items.map(x=><article className={"writing "+x.type.toLowerCase()} key={x.id}><span>{x.type}</span><h3>{x.title}</h3><p>{x.content}</p><em>{x.isPublic?"Public":"Private"}</em></article>)}</section>}
createRoot(document.getElementById("root")).render(<App/>);