import { motion, AnimatePresence } from 'framer-motion';
import { X } from 'lucide-react';

export default function Blog({ SectionTitle, Card, blogs, blog, setBlog }) {
  return <>
    <section id="blog" className="border-y border-zinc-200 bg-white/60 px-6 py-24 dark:border-white/5 dark:bg-white/[.015]"><div className="mx-auto max-w-6xl"><SectionTitle eyebrow="Blog" title="Notes from the build process." /><div className="grid gap-6 md:grid-cols-2">{blogs.length ? blogs.map((item) => <button key={item.id} onClick={() => setBlog(item)} className="text-left"><Card className="overflow-hidden p-0 transition hover:-translate-y-1 hover:border-cyan-400/30"><img src={item.thumbnailUrl} alt={item.title} loading="lazy" className="aspect-video w-full object-cover" /><div className="p-6"><p className="text-xs text-cyan-500">{item.publishedDate}</p><h3 className="mt-2 text-xl font-bold">{item.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">{item.summary}</p></div></Card></button>) : <Card className="p-8 text-center text-zinc-500 md:col-span-2">New Java and Spring Boot articles are coming soon.</Card>}</div></div></section>
    <AnimatePresence>{blog && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[80] flex items-center justify-center bg-black/70 p-5 backdrop-blur-sm" onClick={() => setBlog(null)}><motion.div initial={{ y: 25, scale: .98 }} animate={{ y: 0, scale: 1 }} onClick={(event) => event.stopPropagation()} className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-white/10 bg-white p-7 text-slate-900 dark:bg-[#111118] dark:text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-cyan-500">{blog.publishedDate}</p><h3 className="mt-2 text-2xl font-black">{blog.title}</h3></div><button onClick={() => setBlog(null)} aria-label="Close blog"><X /></button></div><p className="mt-6 whitespace-pre-wrap leading-8 text-zinc-700 dark:text-zinc-300">{blog.content}</p></motion.div></motion.div>}</AnimatePresence>
  </>;
}
