INSERT INTO skill (name, category, proficiency_percent) VALUES
('Java', 'Backend', 90), ('Spring Boot', 'Backend', 85), ('Spring Security', 'Backend', 75), ('JWT', 'Backend', 75), ('Hibernate/JPA', 'Backend', 80), ('MySQL', 'Database', 85), ('React.js', 'Frontend', 75), ('Git', 'Tools', 85), ('Maven', 'Tools', 80), ('Postman', 'Tools', 80);

INSERT INTO project (title, description, tech_stack, github_url, live_demo_url, image_url, featured) VALUES
('AI-Driven Sales Forecasting', 'AI-powered sales forecasting platform with business intelligence dashboards and predictive insights.', 'Java, Spring Boot, MySQL, React, Python, FastAPI', 'https://github.com/prashantpiyush1111/AI-Driven-Sales-Forecasting', 'https://github.com/prashantpiyush1111/AI-Driven-Sales-Forecasting', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80', true),
('RAG Educational Assistant', 'Educational assistant that retrieves relevant knowledge and generates grounded answers from learning resources.', 'Java, Spring Boot, React, Python, RAG, Qdrant', 'https://github.com/prashantpiyush1111/rag-educational-system', 'https://github.com/prashantpiyush1111/rag-educational-system', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80', true),
('Task Management System', 'Jira-style task management system with assignments, role-based permissions, deadlines, and collaboration.', 'Java, Spring Boot, MySQL, React, JWT', 'https://github.com/prashantpiyush1111', 'https://github.com/prashantpiyush1111', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80', false);

INSERT INTO blog (title, summary, content, published_date, thumbnail_url) VALUES
('Building REST APIs with Spring Boot', 'A practical overview of clean REST API design with Spring Boot.', 'Spring Boot makes it straightforward to build maintainable REST APIs. Start with resource-focused controllers, move business rules into services, and keep persistence concerns inside repositories. Validate incoming data at the boundary and return consistent error responses.', '2026-08-20', 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80'),
('Spring Data JPA: From Entity to Repository', 'How JPA entities and repositories simplify database access in Java applications.', 'Spring Data JPA removes much of the repetitive persistence code. Define an entity that models your table, create a JpaRepository, and let Spring generate common CRUD operations. As the project grows, put domain logic in services and keep controllers thin.', '2026-09-05', 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1200&q=80');
